"""empty message

Revision ID: 56f76118181d
Revises: f4c21269287e
Create Date: 2018-03-20 13:31:48.579000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56f76118181d'
down_revision = 'f4c21269287e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('weather')
    op.add_column('environment', sa.Column('IP', sa.String(length=24), nullable=True))
    op.add_column('environment', sa.Column('city', sa.String(length=24), nullable=True))
    op.add_column('environment', sa.Column('country', sa.String(length=24), nullable=True))
    op.add_column('environment', sa.Column('description', sa.String(length=64), nullable=True))
    op.add_column('environment', sa.Column('high', sa.Integer(), nullable=True))
    op.add_column('environment', sa.Column('latitude', sa.DECIMAL(precision=6, scale=4), nullable=True))
    op.add_column('environment', sa.Column('longitude', sa.DECIMAL(precision=6, scale=4), nullable=True))
    op.add_column('environment', sa.Column('low', sa.Integer(), nullable=True))
    op.add_column('environment', sa.Column('state', sa.String(length=24), nullable=True))
    op.add_column('environment', sa.Column('sunrise', sa.DateTime(), nullable=True))
    op.add_column('environment', sa.Column('sunset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environment', 'sunset')
    op.drop_column('environment', 'sunrise')
    op.drop_column('environment', 'state')
    op.drop_column('environment', 'low')
    op.drop_column('environment', 'longitude')
    op.drop_column('environment', 'latitude')
    op.drop_column('environment', 'high')
    op.drop_column('environment', 'description')
    op.drop_column('environment', 'country')
    op.drop_column('environment', 'city')
    op.drop_column('environment', 'IP')
    op.create_table('weather',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('low', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('high', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('sunrise', mysql.DATETIME(), nullable=True),
    sa.Column('sunset', mysql.DATETIME(), nullable=True),
    sa.Column('environment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], [u'environment.id'], name=u'weather_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('location',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('latitude', mysql.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('longitude', mysql.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=24), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=24), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=24), nullable=True),
    sa.Column('IP', mysql.VARCHAR(length=24), nullable=True),
    sa.Column('environment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], [u'environment.id'], name=u'location_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
