"""empty message

Revision ID: 6b4151a6ca63
Revises: b70e9a5e2758
Create Date: 2018-03-13 16:36:29.884000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b4151a6ca63'
down_revision = 'b70e9a5e2758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_types_type'), 'device_types', ['type'], unique=True)
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_name'), 'environment', ['name'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_state'), 'states', ['state'], unique=True)
    op.create_table('user_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_types_type'), 'user_types', ['type'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('country', sa.String(length=24), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=True),
    sa.Column('city', sa.String(length=24), nullable=True),
    sa.Column('IP', sa.String(length=24), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('low', sa.Integer(), nullable=True),
    sa.Column('high', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('sunrise', sa.DateTime(), nullable=True),
    sa.Column('sunset', sa.DateTime(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('IP', sa.String(length=24), nullable=True),
    sa.Column('MAC', sa.String(length=24), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.Column('device_type', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_type'], ['device_types.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['state'], ['states.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('MAC')
    )
    op.create_index(op.f('ix_device_last_online'), 'device', ['last_online'], unique=False)
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=False)
    op.add_column(u'user', sa.Column('environment_id', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('last_online', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('user_type', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_last_online'), 'user', ['last_online'], unique=False)
    op.create_foreign_key(None, 'user', 'environment', ['environment_id'], ['id'])
    op.create_foreign_key(None, 'user', 'user_types', ['user_type'], ['id'])
    op.drop_column(u'user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('last_seen', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_last_online'), table_name='user')
    op.drop_column(u'user', 'user_type')
    op.drop_column(u'user', 'last_online')
    op.drop_column(u'user', 'environment_id')
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_index(op.f('ix_device_last_online'), table_name='device')
    op.drop_table('device')
    op.drop_table('weather')
    op.drop_table('location')
    op.drop_index(op.f('ix_user_types_type'), table_name='user_types')
    op.drop_table('user_types')
    op.drop_index(op.f('ix_states_state'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_environment_name'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_device_types_type'), table_name='device_types')
    op.drop_table('device_types')
    # ### end Alembic commands ###
