"""empty message

Revision ID: d3c88021680f
Revises: d75f1e90902d
Create Date: 2018-03-15 16:15:58.153000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3c88021680f'
down_revision = 'd75f1e90902d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('state_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'user_ibfk_3', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'states', ['state_id'], ['id'])
    op.drop_column('user', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(u'user_ibfk_3', 'user', 'states', ['state'], ['id'])
    op.drop_column('user', 'state_id')
    # ### end Alembic commands ###
