"""empty message

Revision ID: d75f1e90902d
Revises: e8624fd41797
Create Date: 2018-03-15 16:00:12.870000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75f1e90902d'
down_revision = 'e8624fd41797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('state', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'states', ['state'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'state')
    # ### end Alembic commands ###
