"""empty message

Revision ID: e8624fd41797
Revises: 418377f91bbd
Create Date: 2018-03-15 12:28:36.239000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8624fd41797'
down_revision = '418377f91bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_type_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'device_ibfk_1', 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'device_types', ['device_type_id'], ['id'])
    op.drop_column('device', 'device_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key(u'device_ibfk_1', 'device', 'device_types', ['device_type'], ['id'])
    op.drop_column('device', 'device_type_id')
    # ### end Alembic commands ###
